=== Catlovi/WarOfCastles/castles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Castles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Castle" maxOccurs="8">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Attack" type="xs:int"/>
                            <xs:element name="Defense" type="xs:int"/>
                            <xs:element name="Benefit" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Catlovi/WarOfCastles/castles.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="castles.xslt"?>
<Castles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="castles.xsd">
    
    <Castle id="1">
        <Name>Oudaïas Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Transform 2% of player attack points into defense points</Benefit>
    </Castle>

    <Castle id="2">
        <Name>Miravalle Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Transform 2% of player defense points into attack points</Benefit>
    </Castle>

    <Castle id="3">
        <Name>Versailles Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Give 2 additional cannoneers depending on castles owned</Benefit>
    </Castle>

    <Castle id="4">
        <Name>Schönbrunn Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Give 3 additional medics depending on castles owned</Benefit>
    </Castle>

    <Castle id="5">
        <Name>Topkapı Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Multiply army attack points by 1.05 depending on castles owned</Benefit>
    </Castle>

    <Castle id="6">
        <Name>Kremlin Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Multiply army defense points by 1.05 depending on castles owned</Benefit>
    </Castle>

    <Castle id="7">
        <Name>Himeji Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Give 2 additional archers depending on castles owned</Benefit>
    </Castle>

    <Castle id="8">
        <Name>Buckingham Castle</Name>
        <Attack>2500</Attack>
        <Defense>2500</Defense>
        <Benefit>Give 2 additional knights depending on castles owned</Benefit>
    </Castle>

</Castles>
