=== Catlovi/WarOfCastles/villages.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Villages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Village" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="TroopProduction">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Troop" type="TroopType" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definitions des troops -->
    <xs:complexType name="TroopType">
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="quantity" type="xs:int" use="required"/>
    </xs:complexType>

</xs:schema>

=== Catlovi/WarOfCastles/villages.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="villages.xslt"?>
<Villages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="villages.xsd">

    <Village id="1">
        <Name>Village near Oudaïas Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>

    <Village id="2">
        <Name>Village near Miravalle Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>

    <Village id="3">
        <Name>Village near Versailles Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>

    <Village id="4">
        <Name>Village near Schönbrunn Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>

    <Village id="5">
        <Name>Village near Topkapı Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>

    <Village id="6">
        <Name>Village near Kremlin Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>

    <Village id="7">
        <Name>Village near Himeji Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>

    <Village id="8">
        <Name>Village near Buckingham Castle</Name>
        <TroopProduction>
            <Troop type="Knight" quantity="2"/>
            <Troop type="Archer" quantity="2"/>
            <Troop type="Cannoneer" quantity="2"/>
            <Troop type="Medic" quantity="2"/>
        </TroopProduction>
    </Village>
</Villages>
